# Generated by Django 5.0.1 on 2024-02-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cuisine_types",
            field=models.CharField(
                choices=[
                    ("caribbean", "Caribbean"),
                    ("asian", "Asian"),
                    ("vegetarian", "Vegetarian"),
                    ("european", "European"),
                    ("desserts", "Desserts"),
                ],
                default="european",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("dinner", "Dinner"),
                    ("light bites", "Light Bites"),
                    ("dessert", "Dessert"),
                ],
                default="dinner",
                max_length=50,
            ),
        ),
    ]
